Fixes #37526 - Remove python3-tracer package from el8
Katello/katello-host-tools pull request #158
Opened 2024-06-03 10:52 UTC by archanaserver

2024-06-03 10:58 UTC, ekohl requested changes
Since 1408cbd8ca29d1a921a69e7f0f21597fe097e3c9 it's no longer a dependency and you can also remove it from other places.

2024-06-04 09:22 UTC, ekohl commented
Please rebase now that EL8 is fixed.

2024-06-22 07:51 UTC, sbernhard approved these changes
Make sense. thanks.

2024-06-22 08:54 UTC, ekohl approved these changes

2024-06-22 08:54 UTC, merged